const assocImages = {
    '1': 'assets/img_cartes/virus.png',
    '2': 'assets/img_cartes/point.png',
    '3': 'assets/img_cartes/fighter.png',
    '4': 'assets/img_cartes/remplissagefosse.png',
    '5': 'assets/img_cartes/antidote.png',
    '6': 'assets/img_cartes/fossecreuse.png',
    '7': 'assets/img_cartes/vote.png',
    '8': 'assets/img_cartes/zodiac.png',
    '9': 'assets/img_cartes/sanction.png',
    '10': 'assets/img_cartes/lion.png',
    '11': 'assets/img_cartes/path.png',
    '12': 'assets/img_cartes/girl.png',
    '13': 'assets/img_cartes/embryo.png',
    '14': 'assets/img_cartes/fosseboire.png',
    '15': 'assets/img_cartes/meduse.png',
    '16': 'assets/img_cartes/virus2.png',
    '17': 'assets/img_cartes/antidote2.png',
    '18': 'assets/img_cartes/oneangel.png',
    '19': 'assets/img_cartes/threeangels.png',
    '20': 'assets/img_cartes/alumette.png',
    '21': 'assets/img_cartes/debordement.png',
    '22': 'assets/img_cartes/eclate.png',
    '23': 'assets/img_cartes/duelfight.png',
    '24': 'assets/img_cartes/bowling.png',
    '25': 'assets/img_cartes/game.png',
    '26': 'assets/img_cartes/hidepng.png',
    '27': 'assets/img_cartes/storm.png',
    '28': 'assets/img_cartes/mouth.png',
    '29': 'assets/img_cartes/chance.png',
    '30': 'assets/img_cartes/collectif.png',
    '31': 'assets/img_cartes/solo_working.png',
    '32': 'assets/img_cartes/solo_kneel.png',
    '33': 'assets/img_cartes/larva.png',
    '34': 'assets/img_cartes/draw.png',
    '35': 'assets/img_cartes/math_flower.png',
    '36': 'assets/img_cartes/pop_bottle.png',
    '37': 'assets/img_cartes/tooth.png',
    '38': 'assets/img_cartes/fire.png',
    '39': 'assets/img_cartes/city.png',
    '40': 'assets/img_cartes/dummy.png',
    '41': 'assets/img_cartes/satanic.png',
    '42': 'assets/img_cartes/man_in_bottle.png',
    '43': 'assets/img_cartes/totem.png',
    '44': 'assets/img_cartes/soupeserve.png',
    '45': 'assets/img_cartes/sabre.png',
    '46': 'assets/img_cartes/musique.png',
    '47': 'assets/img_cartes/demolition.png',
    '48': 'assets/img_cartes/question.png',
    '49': 'assets/img_cartes/plantt.png',
    '50': 'assets/img_cartes/analyze.png',
    '51': 'assets/img_cartes/paptoilet.png',
    '52': 'assets/img_cartes/roots.png',
    '53': 'assets/img_cartes/GOAT.png',
    '54': 'assets/img_cartes/dynamite.png',
    '55': 'assets/img_cartes/drawsmiley.png',
    '56': 'assets/img_cartes/portal.png',
    '57': 'assets/img_cartes/bubbles.png',
    '58': 'assets/img_cartes/cerveau.png',
    '59': 'assets/img_cartes/coeurbris.png',
    '60': 'assets/img_cartes/implosing.png',
    '61': 'assets/img_cartes/maman.png',
    '62': 'assets/img_cartes/pharma.png',
    '63': 'assets/img_cartes/7peches.png',
    '64': 'assets/img_cartes/bottle_medit.png',
    '65': 'assets/img_cartes/passe.png',
    '66': 'assets/img_cartes/present.png',
    '67': 'assets/img_cartes/futur.png'
}

const assocCode = {
    'LSTCDESAMAJ': ["classique", "test", "baud", "wanted", "neurchi","suddeslandes"],
    'classique': {
        'titreMenu': [
            "On joue ?",
            "On se la colle ?",
            "On vient se la mettre ?",
            "On vient se déboiter ?",
            "On prend sa cuite ?",
            "On prend une biture ?",
            "On a soif ?",
            "On s'arrache la face ?",
            "On vient se démolir ?",
            "On s'éclate la tronche ?",
            "On se met une murge ?",
            "On se pète la ruche ?",
            "On se torpille le caisson ?",
            "On se remplit le cornet ?",
            "On se retourne la tête ?",
            "On se prend une timbale ?"
        ],
        'imgAcc': 'assets/selecjoueurs.png',
        'titreSlider': '###',
        'grpCarte': '(1)'
    },
    'wanted': {
        'titreMenu': [
            "On joue ?",
            "On se la colle ?",
            "On vient se la mettre ?",
            "On vient se déboiter ?",
            "On prend sa cuite ?",
            "On prend une biture ?",
            "On a soif ?",
            "On s'arrache la face ?",
            "On vient se démolir ?",
            "On s'éclate la tronche ?",
            "On se met une murge ?",
            "On se pète la ruche ?",
            "On se torpille le caisson ?",
            "On se remplit le cornet ?",
            "On se retourne la tête ?",
            "On se prend une timbale ?"
        ],
        'imgAcc': 'assets/selecjoueurs.png',
        'titreSlider': '###',
        'grpCarte': '(1)'
    },
    'neurchi': {
        'titreMenu': [
            "On joue ?",
            "On se la colle ?",
            "On vient se la mettre ?",
            "On vient se déboiter ?",
            "On prend sa cuite ?",
            "On prend une biture ?",
            "On a soif ?",
            "On s'arrache la face ?",
            "On vient se démolir ?",
            "On s'éclate la tronche ?",
            "On se met une murge ?",
            "On se pète la ruche ?",
            "On se torpille le caisson ?",
            "On se remplit le cornet ?",
            "On se retourne la tête ?",
            "On se prend une timbale ?"
        ],
        'imgAcc': 'assets/accueilNeurchi.png',
        'titreSlider': '###',
        'grpCarte': '(1)'
    },
    'test': {
        'titreMenu': ['*titre aléatoire customisé*'],
        'imgAcc': 'assets/demologo.png',
        'titreSlider': '###',
        'grpCarte': '(1,11)'
    },
    'baud': {
        'titreMenu': ['Baud <3'],
        'imgAcc': 'assets/selecjoueurs.png',
        'titreSlider': '###',
        'grpCarte': '(1,11)'
    },
    'suddeslandes': {
        'titreMenu': ['Sud des Landes'],
        'imgAcc': 'assets/selecjoueurs.png',
        'titreSlider': '###',
        'grpCarte': '(1,11)'
    }
}